import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DSA Instructor AI',
  description: 'Generated by Aion Web',
  icons: {
    icon: '/favicon.ico', // You'll need to place a favicon.ico in your `public` directory
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
